[ODS-4183] Migrate Ed-Fi-MigrationUtility to the OSS Repository
Ed-Fi-Alliance-OSS/Ed-Fi-MigrationUtility pull request #2
Opened 2020-05-18 17:38 UTC by semalaiappan

2020-05-18 20:27 UTC, jamessmckay requested changes

2020-05-18 20:27 UTC, jamessmckay commented on Migration.sln
> +VisualStudioVersion = 15.0.28307.902
revert this change

2020-05-18 21:34 UTC, semalaiappan commented on Migration.sln
> +VisualStudioVersion = 15.0.28307.902
Done . Thanks

2020-05-19 13:04 UTC, jamessmckay approved these changes

2020-05-19 13:05 UTC, merged